name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: davidB/rust-cargo-make@v1
      with:
        version: '0.23.0'
    - uses: actions/checkout@v3
    - name: Build
      run: cargo make
    - name: Run tests
      run: cargo test
